### ISSUE TITLE
[Feat] 작성 일기 뷰 기본 UI & 기본 로직 구현

### ISSUE THREAD

**Issue by kim-seonwoo** [Donkeys-today/Clody_iOS#17]
## 💡 About

- 작성 일기 뷰 기본 UI를 구현합니다
- 기본 로직을 구현합니다
- 동적 텍스트를 구현합니다

## ☑️ TO-DO LIST

- [ ] 작성 일기 뷰 기본 UI를 구현합니다
- [ ] 기본 로직을 구현합니다
- [ ] 동적 텍스트를 구현합니다
