### ISSUE TITLE
[Feat] 프로필 및 계정관리 뷰 닉네임 변경

### ISSUE THREAD

**Issue by SeoyoungOhMe** [Donkeys-today/Clody_iOS#20]
## 💡 About

- 프로필 및 계정관리 뷰 닉네임 변경 팝업 구현
- 프로필 및 계정관리 뷰 네비게이션 바 추가 
- 설정 뷰 네비게이션 바 추가
- enum 목록 string 파일에 추가하기

## ☑️ TO-DO LIST

- [x] 프로필 및 계정관리 뷰 닉네임 변경 팝업 구현
- [x] 프로필 및 계정관리 뷰 네비게이션 바 추가 
- [x] 알림 설정 뷰 네비게이션 바 추가
- [x] 설정 뷰 네비게이션 바 추가
- [x] 프로필 및 계정관리 뷰 로그아웃, 회원탈퇴 모달창 구현
- [x] 알림 설정 뷰 알림 시간 설정 피커뷰 구현
- [x] 파일 간 이동 구현
- [x] enum 목록 string 파일에 추가하기
- [x] 텍스트 필드 글자수, 입력 문자 제한 기능 구현
- [x] 상단의 불필요한 네비게이션 삭제
- [ ] 뷰모델 input, output 나눠서 각각 연결
- [ ] AccountVC의 글자수 반영 문제 해결하기
