### ISSUE TITLE
[Feat] 일기 답장 화면 UI 구현

### ISSUE THREAD

**Issue by Nya128** [Donkeys-today/Clody_iOS#22]
## 💡 About

- 일기 답장 확인 화면을 구현합니다.
- 데모데이를 위해 기존의 12시간이 아닌 1분 타이머를 구현합니다.
- PR 크기가 크지 않다면 Rx도 같이 붙여보도록 하겠습니다!! 😵‍💫

## ☑️ TO-DO LIST

- [x] 답장 대기 화면 (타이머 돌아감)
- [x] 답장 도착 화면 (타이머 0초)
- [x] 네잎클로버 획득 Alert
- [x] 답장 조회 화면
