### ISSUE TITLE
[Feat] Alarm권한 메니저 파일 추가

### ISSUE THREAD

**Issue by kim-seonwoo** [Donkeys-today/Clody_iOS#49]
## 💡 About

- 애플에서 제공하는 알림 관련 싱글톤 생성
- 에러 핸들링

## ☑️ TO-DO LIST

- [ ] 🍀 답장 확인한 거면 네잎클로버 획득창 다시 안 뜨게(isNew)
- [ ] 초기값 뜨는 문제 (내비바, 피커뷰: 초기값으로 세팅해줘야됨)
- [ ] 🍀알림 권한 (온보딩)
