### ISSUE TITLE
[Fix] QA 반영

### ISSUE THREAD

**Issue by Nya128** [Donkeys-today/Clody_iOS#56]
## 💡 About

- QA 수정 사항 반영하기~🥹

## ☑️ TO-DO LIST

- [x]  ⭐️ 리스트뷰에서 답장확인 누르면 푸시가 두번 됨 -> 이젠 세번임ㅋㅋ (선우) (나연)
- [x]  온보딩 서브타이틀이 중앙정렬이 안 됨 (나연)
- [x]  온보딩 일러스트 수정 (나연)
- [x]  메인에서 캘린더와 일기 구분선 추가 (선우)
- [x]  작성 알림에서 뒤로가기 버튼 제거 (나연)
- [x]  작성알림에서 다운 이미지뷰 눌렀을 때는 바텀시트 안 뜸 (나연)
- [x]  피커뷰 초기값 세팅 (선우)
- [x]  ⭐️ 토스트 메시지 레이아웃 수정 + 5개인데도 토스트 뜨는 문제 (선우)
- [x]  작성할 때 날짜 월에서 0을 빼세요 (선우)
- [x]  ⭐️ viewWillApear()에서 캘린더/리스트 fetchData 필요 (선우)
- [x]  ⭐️ 타이머 …. 시간 계산이 안 되지? (나연)
- [x]  피커뷰 간격 수정 (선우) (나연)
- [x]  리스트뷰셀에서 답장 도착안했으면 클로버 회색 (선우)
- [x]  editing 중일 때 작성 완료 버튼을 누르면 토스트 메시지가 뜸. (선우)
- [x]  리스트뷰셀에서 요일 UI, 레이아웃 다시 잡기 (선우)
- [x] 닉네임 변경 바텀시트 UI, 레이아웃 수정(특히 '변경하기' 버튼 safeAreaLayoutGuide로 바꾸기)
- [x] 닉네임 변경 바텀시트 애니메이션 처리
- [ ] 알림 시간 설정 바텀시트 애니메이션 처리
- [x] 온보딩 알림 설정 화면 바텀시트 x버튼 탭 안됨
