### ISSUE TITLE
[Feat] 온보딩 디테일 작업

### ISSUE THREAD

**Issue by Nya128** [Donkeys-today/Clody_iOS#61]
## 💡 About

- 릴리즈를 위해 온보딩 과정 중 빠진 부분 다 구현합니다.

## ☑️ TO-DO LIST

- [x] 이메일 화면 UI 구현
- [x] 애플 로그인 API, 회원가입 API
- [x] 닉네임, 이메일 유효성 검사
- [x] 이메일 입력할 때 이메일 키보드 나오게
- [ ] 이메일 글자수 제한?
- [x] 이용약관, 개인정보 처리방침 링크 연결 (설정에도 있음)
- [x] 로그아웃 처리
- [x] 애니메이션 없는 바텀시트 수정
- [x] 설정 alert에서 dimmingView 탭했을 때 아무 일도 일어나면 안 되게
- [x] 닉네임 텍스트필드에서 x버튼 안 보이는 문제
- [ ] 타이머
