### ISSUE TITLE
[Feat] 릴리즈 QA 전 구현할 것들

### ISSUE THREAD

**Issue by Nya128** [Donkeys-today/Clody_iOS#73]
## 💡 About

- 릴리즈 QA 전 미구현 사항들 완성하기

## ☑️ TO-DO LIST

- [x] 온보딩 에러 대응 (로딩 인디케이터 포함) 안 한 거 다 하기
- [x] 설정 에러 대응 
- [x] 성공시 토스트메시지
- [x] 무한로딩 걸리는지 확인
- [x] 알림 설정 피커뷰 현재 설정한 시간으로 반영하기
- [x] 타이머
- [x] 타이머 최초 1회 답장인지 분기처리
- [x] 답장 대기 화면 - 재시도 뷰
- [x] 답장 상세 화면 - 재시도 뷰
- [x] 네잎클로버 획득창 닉네임 바인딩
- [x] 노션링크 바뀐거 넣어야함
- [x] 계정 카카오/애플 에셋 구분
