### ISSUE TITLE
[Fix] 디자인 QA 반영

### ISSUE THREAD

**Issue by kim-seonwoo** [Donkeys-today/Clody_iOS#74]
## 💡 About

-디자인 QA 반영

## ☑️ TO-DO LIST

- [x] 톱니바퀴 사이즈 조정 (키워서 시각적 보정 필요함)
- [x] 캘린더 뷰 메인 내용 폰트 수정 (숫자 폰트 제외)
- [x] 케밥 아이콘 클릭 시 나타나는 모달 아이콘, 폰트 사이즈 확대
- [x] "아직 감사 일기가 없어요!" 위치 수정
- [x] 캘린더 뷰 구분선 두께 수정 필요
- [x] 캘린더 뷰 구분선 간격 조정
- [x] iOS 온보딩 설명 텍스트 행간 조정
- [x] iOS 프로필 및 계정 관리에서 사용자 아이콘 이미지 깨짐
- [x] 프로필 및 계정 관리 구분선 색상 잘못 반영됨
- [ ] 설정 구분선과 내용 간의 간격이 잘못 반영됨
- [x] 다른 날짜 보기 하단 숫자와 완료 버튼 사이 간격 수정 필요
