### ISSUE TITLE
[Fix] v1.0.0 릴리즈 리젝 사항 수정

### ISSUE THREAD

**Issue by Nya128** [Donkeys-today/Clody_iOS#79]
## 💡 About

- v1.0.0 릴리즈 리젝 사항 반영

## ☑️ TO-DO LIST

- [x] 최초 답장 1분 타이머 로직 수정
- [x] 애플 로그인 시 이메일 받아와서 키체인에 저장
- [x] 이메일 화면 삭제
- [x] 텍스트필드 이메일 타입 삭제
- [x] 일기 작성 글자수 에러메시지 수정
- [x] 지원기기에서 아이패드 제외
