### ISSUE TITLE
[Feat] 릴리즈 후 디테일 및 기능 업데이트 

### ISSUE THREAD

**Issue by Nya128** [Donkeys-today/Clody_iOS#82]
## 💡 About

- 1차 릴리즈 후 반영할 뷰 디테일 및 기능 업데이트를 진행합니다.

## ☑️ TO-DO LIST

- [ ] 설정 화면 코드 리팩토링
- [ ] 설정 화면 디자인 QA(테이블뷰 간격 정확하게 조정) 반영
- [x] 🌐 캘린더나 리스트 뷰컨에서만 isNew를 처리해서 그걸로 쭉 쓰는게 문제… 
답장 대기 화면에서 UNREADY 상태였다가 READY_NOT_READ로 바뀔 수 있는데, 처음에 받아온걸로 쭉 사용하기 때문에 상태가 업뎃이 안 됨 -> 네잎클로버 획득창이 안 뜸!!!
- [ ] 🌐 같은 계정인데 2개의 폰에서 쓸 때… 다른 폰으로 탈퇴하고, 원래 폰에서 다시 접속하면 캘린더 조회가 가능함. 
캘린더 월 단위 조회할 때만 존재하는 사용자인지 확인하는 기능 서버에 부탁하기. + 캘린더 화면 에러대응 추가
- [ ] 🌐 애플 탈퇴할 때 revoke api 애플 서버에 보내주는 거 꼬옥 필요… 그거 없으면 당분간 애플 회원가입때 이메일 공백이면 에러 처리라도 해주삼… 
- [x] 바텀시트 센터로 레이아웃 조정
- [x] 타이머 시간 viewWillAppear에서 설정하는 걸로 수정 (백그라운드 상태에서 다시 앱 진입했을 때 시간이 밀리는 문제)
