### ISSUE TITLE
[Fix] 디자인 QA 사항 적용 (for 1.0.3)

### ISSUE THREAD

**Issue by kim-seonwoo** [Donkeys-today/Clody_iOS#87]
## 💡 About

- 헬프 메세지 버튼
- 헬프 메세지 레이아웃
- 헬프메세지 아이콘 
- 일기 작성 배경 활성화 색

## ☑️ TO-DO LIST

- [ ] 헬프 메세지 버튼
- [ ] 헬프 메세지 레이아웃
- [ ] 헬프메세지 아이콘 
- [ ] 일기 작성 배경 활성화 색
