### ISSUE TITLE
[Feat] 공통 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by Nya128** [Donkeys-today/Clody_iOS#9]
## 💡 About

- 텍스트 필드, 피커뷰, 버튼처럼 여러 번 사용되는 공통 UI 컴포넌트를 구현한다.
- 동적으로 변할 수 있는 사항(텍스트, 내부 패딩 등)은 생성자 Parameter로 받아서 만들 것.
- Clody 넣어서 커스텀 컴포넌트 만들 것.

## ☑️ TO-DO LIST

- [x] 이메일/닉네임 텍스트필드 UI
- [x] 노란 하단 버튼 UI (활성화 상태도 고려)
- [x] PickerView 만들기 (기종 해상도 고려)
- [x] NavigationBar 만들기 (모든 상황 고려)
- [x] Custom Alert
